### ISSUE TITLE
enable bolt on kb.virtualflybrain.org

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/pipeline#15]
Bolt is enabled on kbw port 7688

This doesn't appear to be the case on kb.virtualflybrain.org.  It would be very helpful if these were brought in sync as I'd like to use kb to run travis CI tests on https://github.com/VirtualFlyBrain/VFB_neo_kb_2_owl

**Comment by dosumis** [comment]
@Robbie1977: Seems that this has been done but is preventing login to web interface?

**Comment by Robbie1977** [comment]
Not accessible from outside the firewall. I'll chase the ticket - suspect it got held up with hardware builds which are ongoing.

**Comment by dosumis** [comment]
Fixed (bolt://kb.virtualflybrain.org:7687)
