### ISSUE TITLE
Role: developer; what: OLS loader loads all OWL needed to run site; why:  less code to run & maintain

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/pipeline#16]

**Comment by dosumis** [comment]
User story for displaying missing anonymous type data:  As user I want the properties of anatomical structures depicted in images to be displayed and queryable so that I can understand and navigate this content.

Implementation: See EBISPOT/OLS#13

**Comment by dosumis** [comment]
Awaiting review with Simon.

@matentzn will look at how well this is working in a container and report back.

**Comment by matentzn** [comment]
Code review with Simon complete. Pull request [here](https://github.com/EBISPOT/OLS/pull/187).
