### ISSUE TITLE
FBbt used in 1.5 is out of date/broken

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/pipeline#20]
Many of the new anatomy terms present in FB2 are not in VFB1.5, e.g. medulla columnar neuron VPN-MB2, lobula layer 5A, larval A02d neuron. Others such as lobula columnar neuron LC10 are present in both. 

Current FBbt used by FB2 is frozen here http://flybase.org/cgi-bin/get_static_page.pl?file=bulkdata7.html&title=Current%20Release

Linkouts to current VFB also broken as a result, e.g. from this page
http://flybase.org/cgi-bin/cvreport.pl?id=FBbt%3A00111743
takes you to adult brain on VFB

**Comment by Robbie1977** [comment]
This was an issue with the search (SOLR on blanik) having the wrong OWL loaded (from vfbdev). This has been changed to load from the version on vfbsandbox.
