### ISSUE TITLE
Specify system for testing and ensuring label uniqueness for object properties in NeoKB and Prod

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/pipeline#21]
Object properties are added as nodes by both the KB loader and OLS (prod) loader.  It should therefore be possible to ensure property label uniqueness by adding the appropriate uniqueness constraint to Neo4J.  

Questions:
   1. How will this constraint work with loading via Java API.  If loading via cypher, the loading constraint would cause a load fail.
  2. We don't control all input ontologies.  What strategy should we use for dealing with cases where loading ontologies => two OPs with same label.

**Comment by matentzn** [comment]
@dosumis Do I see this correctly that this ticket is served by your qualified safe label solution?

**Comment by matentzn** [comment]
Reopen if necessary, but I believe this should be solved.
