### ISSUE TITLE
Write formal documentation of new neo4j to OWL mapping

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/pipeline#29]

**Comment by matentzn** [comment]
The mapping is now documented [here]( https://github.com/matentzn/neo4j2owl).

The next step is to create a reference implementation.

**Comment by matentzn** [comment]
I have added the remaining comment on how the safe labels are constructed. @dosumis  Feel free to edit the spec directly in GitHub, I wont touch it until this ticket is cleared from QC.
