### ISSUE TITLE
Implement generic typing system for neo nodes

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/pipeline#43]
yaml or spreadsheet or key-value based:
entity-iri:nodetype
http://test.owl#Neuron:Neuron, meaning that all instances of Neuron should be typed as Neuron as well.

**Comment by dosumis** [comment]
MVP:
list of classes - all instances and subclasses of which get a Neo:label 
default  rdfs:label 'fu bar' => :Fu_bar.  Optional spec over-ride on name.

Version2: 
Allows class expressions -> Neo:labels.  In this case specification of neo:Label name is compulsory.  TBD - implement by adding defined class or by using DL query.

**Comment by matentzn** [comment]
Note to self:

Allow configs like: 

```
- label:  Neuron_adult
   expressions:     
        - VFB:000002     
        - RO:0000060 some VFB:000001
```

`label` is optional; if not given, use recipes of David in comment above. expressions can be: CURIEs, IRIs, CURIE class expressions or IRI class expressions.

**Comment by dosumis** [comment]
The current list of labels from named classes is in this dict

https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/neo2neo/add_constraints_and_redundant_labels.py#L33

Key = neo label, value = list of classes to which this applies (referred to by label)

Almost all follow the convention 'fu bar' => :Fu_bar.

Current class OWL expression queries: 

https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/owl2neo/add_labels_from_owl_queries.py#L19
