### ISSUE TITLE
Add KB2Prod Jenkins job

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/pipeline#6]
@dosumis commented on [Mon Nov 20 2017](https://github.com/VirtualFlyBrain/geppetto-vfb/issues/113)

Pure Python3 script for direct loading of non-OWL content from KB to Prod
uk.ac.ebi.vfb.neo4j.neo2neo.KB2Prod

**Comment by Robbie1977** [comment]
Testing here: https://travis-ci.org/VirtualFlyBrain/pipeline

**Comment by dosumis** [comment]
Was broken by this issue:
VirtualFlyBrain/pipeline#12
Now fixed

**Comment by Robbie1977** [comment]
Working here: https://blanik.inf.ed.ac.uk:8079/view/Rancher/job/Load%20Production%20DB%20from%20Current%20OWL/

Result here:
http://pdb-firstload.virtualflybrain.org/browser/
