### ISSUE TITLE
Make sure pipeline 2 data collection volume is cleared when pipeline is re-built

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/pipeline#68]
Hey @Robbie1977 I realised there might be a point of failure of the pipeline unaccounted for. In the triplestore portion of the pipeline, the volume that is attached to [vfb-collectdata](https://jenkins.virtualflybrain.org/view/pip_pipeline2/job/pip_vfb-triplestore/configure) should be cleared or in any case fresh each time the pipeline is run. Otherwise it is possible that the data collected from a previous run will be loaded into the triplestore, or even worse, data that has since been discarded from the pipeline but still lives in that directory. Can you clear it as part of the config (linked above)?

**Comment by Robbie1977** [comment]
If we change to an upgrade rather than a restart it should work - I'll have a play

**Comment by Robbie1977** [comment]
https://jenkins.virtualflybrain.org/view/pip_pipeline2/job/pip_vfb-triplestore/configure

Now upgrades rather than restarting which will add a new volume.
