### ISSUE TITLE
Pipeline Collect data seems "unhealthy"

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/pipeline#69]
But I cannot see any logs; Is there any way I can see logs of the last container that ran?

**Comment by Robbie1977** [comment]
Nope as there is no last container hence it's unhealthy - I'll add a job to handle this eventuality as with the earlier jobs

**Comment by Robbie1977** [comment]
@matentzn The last run log is here: https://jenkins.virtualflybrain.org/view/pip_pipeline2/job/pip_vfb-triplestore/52/console

**Comment by Robbie1977** [comment]
https://jenkins.virtualflybrain.org/view/pip_pipeline2/job/upgrade_vfb-collectdata/
Use to fix Nico-Pipeline/vfb-collectdata if unhealthy or you need to force an upgrade
