### ISSUE TITLE
Document KB2Prod for the purpose of getting rid of it.

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/pipeline#71]
We need to know things like sideloading, additional processing etc.

**Comment by dosumis** [comment]
KB to OWL:

  -  Text def generation for individuals:  We should just drop this as an unsustainable overhead.  We may want to review some reports that assume this will be present.
  -  Dynamic calculation of overlap for FlyCircuit neurons.  We should simply hard-wire these into the KB. This could potentially be done by modifying the [Scala code that generates these](https://github.com/VirtualFlyBrain/VFB_neo_kb_2_owl/blob/master/src/main/scala/org/virtualflybrain/neo_kb_2_owl/cypher2OWL.scala#L169) to write back to KBW (Alternatively, there is some ancient Jython that used  to write OWL that could be adapted).   @dosumis 

Side loading PDB: 

FlyBase:  Plan - keep current code (tweaked if necessary).  Longer term aim to migrate to integration layer import.
   - Load pub data
   - Load Expression data & feature relationships

Denormalizing PDB:
   - Expand ontology class -> pub links: This should be dealt with in loading  - see https://github.com/VirtualFlyBrain/neo4j2owl/issues/8 @matentzn 
   - Adding redundant labels based on classification -  Now built into pipeline.

**Comment by dosumis** [comment]
Moved notes to Epic card. Ticket no longer needed.
