### ISSUE TITLE
Clipping of text in queries in firefox

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/pipeline#9]
![image](https://user-images.githubusercontent.com/4630768/33079454-86935cc2-cecd-11e7-946a-68e0ad521f14.png)

**Comment by dosumis** [comment]
Issue moved to [VirtualFlyBrain/geppetto-vfb #117](https://github.com/VirtualFlyBrain/geppetto-vfb/issues/117) via [**ZenHub**](https://www.zenhub.com/)
